export const tableHeading = [
  {
    name: "name",
    subject1: "English Language",
    subject2: "Mathematics",
    subject3: "Civic Education",
    subject4: "Agricultural Studies",
    subject5: "Computer Studies",
    subject6: "Computer Studies",
    subject7: "Computer Studies",
    subject8: "Computer Studies",
    subject9: "Computer Studies",
    subject10: "Computer Studies",
    subject11: "Computer Studies",
    subject12: "Computer Studies",
    total: "Total Score",
    average: "Average",
    position: "Position",
  },
];
export const students = [
  {
    studentName: "Abdussalam Muhammad ",
    subject1: 12,
    subject2: 30,
    subject3: 54,
    subject4: 43,
    subject5: 45,
    subject6: 60,
    subject7: 32,
    subject8: 56,
    subject9: 33,
    subject10: 55,
    subject11: 65,
    subject12: 54,
    // total:students[0]
  },
  {
    studentName: "Zahraddin Wanka",
    subject1: 12,
    subject2: 30,
    subject3: 54,
    subject4: 43,
    subject5: 45,
    subject6: 60,
    subject7: 32,
    subject8: 56,
    subject9: 33,
    subject10: 55,
    subject11: 65,
    subject12: 54,
    // total:students[0]
  },
    {
    studentName: "Mohammed Mustapha Zakari",
    subject1: 12,
    subject2: 30,
    subject3: 54,
    subject4: 43,
    subject5: 45,
    subject6: 60,
    subject7: 32,
    subject8: 56,
    subject9: 33,
    subject10: 55,
    subject11: 65,
    subject12: 54,
    // total:students[0]
  },
];
