const subject = [
    { value: 'ARABIC', id: 1},
    { value: 'AGRICULTURAL SCIENCE', id: 2},
    { value: 'AUTO PARTS MERCHANDISING', id: 3},
    { value: 'AUTO MECHANICS', id: 4},
    { value: 'AUTO ELECTRICAL WORK', id: 5},
    { value: 'AUTO BODY REPAIRS AND SPRAY PAINTING', id: 6},
    { value: 'APPLIED ELECTRICITY OR BASIC ELECTRICITY', id: 7},
    { value: 'ANIMAL HUSBANDRY', id: 8},
    { value: 'BUSINESS MANAGEMENT', id: 9},
    { value: 'BUILDING CONSTRUCTION', id: 10},
    { value: 'BOOK KEEPING', id: 11},
    { value: 'BLOCKLAYING, BRICKLAYING AND CONCRETING', id: 12},
    { value: 'BIOLOGY', id: 13},
    { value: 'BASKETRY', id: 14},
    { value: 'CROP HUSBANDRY AND HORTICULTURE', id: 15},
    { value: 'COSMETOLOGY', id: 16},
    { value: 'COMPUTER STUDIES', id: 17},
    { value: 'COMMERCE', id: 18},
    { value: 'CLOTHING AND TEXTILES', id: 19},
    { value: 'CLERICAL OFFICE DUTIES', id: 20},
    { value: 'CIVIC EDUCATION', id: 21},
    { value: 'CHRISTIAN RELIGIOUS STUDIES', id: 22},
    { value: 'CHEMISTRY', id: 23},
    { value: 'CERAMICS', id: 24},
    { value: 'CATERING CRAFT PRACTICE', id: 25},
    { value: 'CAPENTRY AND JOINERY', id: 26},
    { value: 'DYEING & BLEACHING', id: 27},
    { value: 'DATA PROCESSING', id: 28},
    { value: 'ENGLISH LANGUAGE', id: 29},
    { value: 'ELECTRONICS OR BASIC ELECTRONICS', id: 30},
    { value: 'ELECTRONICS OR BASIC ELECTRONICS', id: 31},
    { value: 'ELECTRICAL INSTALLATION AND MAINTENANCE', id: 32},
    { value: 'EFIK', id: 33},
    { value: 'EDO', id: 34},
    { value: 'ECONOMICS', id: 35},
    { value: 'FURTHER MATHEMATICS', id: 36},
    { value: 'FURNITURE MAKING', id: 37},
    { value: 'FRENCH', id: 38},
    { value: 'FORESTRY', id: 39},
    { value: 'FOODS AND NUTRITION', id: 40},
    { value: 'FISHERIES', id: 41},
    { value: 'FINANCIAL ACCOUNTING', id: 42},
    { value: 'TYPEWRITING', id: 43},
    { value: 'TOURISM', id: 44},
    { value: 'TEXTILES', id: 45},
    { value: 'TECHNICAL DRAWING', id: 46},
    { value: 'STORE MANAGEMENT', id: 47},
    { value: 'STORE KEEPING WAEC', id: 48},
    { value: 'SOCIAL STUDIES', id: 49},
    { value: 'SHORTHAND', id: 50},
    { value: 'SCULPTURE', id: 51},
    { value: 'SALESMANSHIP', id: 52},
    { value: 'REFRIGERATION AND AIR CONDITIONING', id: 53},
    { value: 'RADIO,TELEVISION AND ELECTRONICS WORKS', id: 54},
    { value: 'PRINTING CRAFT PRACTICE', id: 55},
    { value: 'PRINCIPLES OF COST ACCOUNTING', id: 56},
    { value: 'PLUMBING AND PIPE FITTING', id: 57},
    { value: 'PICTURE MAKING', id: 58},
    { value: 'PHYSICS', id: 59},
    { value: 'PHYSICAL EDUCATION', id: 60},
    { value: 'PHOTOGRAPHY', id: 61},
    { value: 'PAINTING AND DECORATING', id: 62},
    { value: 'OFFICE PRACTICE', id: 63},
    { value: 'MUSIC', id: 64},
    { value: 'MINING', id: 65},
    { value: 'METALWORK', id: 66},
    { value: 'MARKETING', id: 67},
    { value: 'MACHINE WOODWORKING', id: 68},
    { value: 'LITERATURE IN ENGLISH', id: 69},
    { value: 'LEATHERWORK', id: 70},
    { value: 'LEATHER GOODS', id: 71},
    { value: 'JEWELLERY', id: 72},
    { value: 'ISLAMIC RELIGIOUS STUDIES', id: 73},
    { value: 'INTEGRATED SCIENCE', id: 74},
    { value: 'INSURANCE', id: 75},
    { value: 'INFORMATION AND COMMUNICATION TECHNOLOGY', id: 76},
    { value: 'IGBO', id: 77},
    { value: 'IBIBIO', id: 78},
    { value: 'HOME MANAGEMENT', id: 79},
    { value: 'HISTORY', id: 80},
    { value: 'HEALTH EDUCATION OR HEALTH SCIENCE', id: 81},
    { value: 'HAUSA', id: 82},
    { value: 'GSM PHONES MAINTENANCE AND REPAIRS', id: 83},
    { value: 'GRAPHIC DESIGN', id: 84},
    { value: 'GOVERNMENT', id: 85},
    { value: 'GHANAIAN LANGUAGES', id: 86},
    { value: 'GEOGRAPHY', id: 87},
    { value: 'GENERAL MATHEMATICS OR MATHEMATICS', id: 88},
    { value: 'GENERAL KNOWLEDGE IN ART', id: 89},
    { value: 'GENERAL AGRICULTURE', id: 90},
    { value: 'GARMENT MAKING', id: 91},
    { value: 'VISUAL ART', id: 92},
    { value: 'UPHOLSTERY', id: 93},
    { value: 'WOODWORK', id: 94},
    { value: 'WEST AFRICAN TRADITIONAL RELIGION', id: 95},
    { value: 'WELDING AND FABRICATION ENGINEERING CRAFT PRACTICE', id: 96},
    { value: 'YORUBA', id: 97}
]

export default subject